#!/usr/bin/env node

const fs = require('fs')

const HOME = process.env.HOME
console.log(`Installing dotfiles for ${HOME}`)
const processDir = (base) => {
  const files = fs.readdirSync(base, {withFileTypes: true})
  files.forEach(file => {
    if (file.name === '.git') {
      return
    }
    const relPath = `${base}/${file.name.replace(/^\.\//, '')}`
    const sourcePath = `${__dirname}/${relPath}`
    const homePath = `${HOME}/${relPath}`
    if (file.isDirectory()) {
      console.log(`Creating directory ${homePath}`)
      fs.mkdirSync(homePath, {recursive:true})
      processDir(`${relPath}`)
    } else {
      if (fs.existsSync(homePath)) {
        const stat = fs.lstatSync(homePath)
        if (stat.isFile()) {
          console.log(`Backing up ${homePath}`)
          fs.renameSync(homePath, `${homePath}.backup`)
        } else if (stat.isSymbolicLink()) {
          console.log(`Removing old symbolic link ${homePath}`)
          fs.rmSync(homePath)
        } else {
          console.log(`Cannot replace directory ${homePath} with a file.`)
          throw new Error()
        }
      }
      console.log(`Linking ${sourcePath} to ${homePath}`)
      fs.symlinkSync(sourcePath, homePath)
    }
  })
}

processDir('.')

